# Generated by Django 5.2.7 on 2025-10-22 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=254, verbose_name='Name of the event')),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('event_date', models.DateField(verbose_name='Event date')),
                ('starts_at', models.TimeField(verbose_name='Start time of event')),
                ('ends_at', models.TimeField(verbose_name='End time of event')),
                ('location', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('price', models.IntegerField()),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Deja en blanco para capacidad ilimitada.', null=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
